ALTER TABLE pst_folders
  MODIFY COLUMN file_size BIGINT NOT NULL DEFAULT '0',
  MODIFY COLUMN file_size_sm BIGINT NOT NULL DEFAULT '0',
  MODIFY COLUMN file_size_md BIGINT NOT NULL DEFAULT '0',
  MODIFY COLUMN file_size_lg BIGINT NOT NULL DEFAULT '0',
  MODIFY COLUMN file_size_cnv_video BIGINT NOT NULL DEFAULT '0';